### ISSUE TITLE
Chapter 2:  ModuleNotFoundError: No module named 'pandavro', 'sqlalchemy'

### ISSUE THREAD

**Issue by Friend09** [kylegallatin/ml-python-cookbook-runner#1]
As I was trying each coding section using the python environment from docker, I got this module not found error. I think this may need to be included into the requirements.txt.

![CleanShot 2023-06-28 at 06 22 13](https://github.com/kylegallatin/ml-python-cookbook-runner/assets/7501015/07c5b2ff-b6d5-4e81-9710-b6e21a401d33)

**Comment by Friend09** [comment]
however, the alternative is to manually pip install the library.

![CleanShot 2023-06-28 at 06 24 53](https://github.com/kylegallatin/ml-python-cookbook-runner/assets/7501015/5041917b-9bdf-4b2f-84ba-328a45792174)

**Comment by Friend09** [comment]
another library to include into the requirements.txt file is sqlalchemy
![CleanShot 2023-06-28 at 06 39 34](https://github.com/kylegallatin/ml-python-cookbook-runner/assets/7501015/95aec123-05c0-4268-91cb-f30d633b40a3)

**Comment by kylegallatin** [comment]
Thanks for raising! https://github.com/kylegallatin/ml-python-cookbook-runner/pull/3
